export const ROUTES = {
  DASHBOARD: "/dashboard",
  AUTHORIZATIONS: "/authorizations",
  SETTINGS: "/settings",
};

export const STATUS_COLORS = {
  pending: {
    bg: "bg-yellow-100",
    text: "text-yellow-800",
    dark: {
      bg: "dark:bg-yellow-900",
      text: "dark:text-yellow-200",
    },
  },
  approved: {
    bg: "bg-green-100",
    text: "text-green-800",
    dark: {
      bg: "dark:bg-green-900",
      text: "dark:text-green-200",
    },
  },
  denied: {
    bg: "bg-red-100",
    text: "text-red-800",
    dark: {
      bg: "dark:bg-red-900",
      text: "dark:text-red-200",
    },
  },
};

export const PRIORITY_LEVELS = {
  high: {
    label: "High",
    color: "text-red-600",
    icon: "AlertTriangle",
  },
  medium: {
    label: "Medium",
    color: "text-yellow-600",
    icon: "AlertCircle",
  },
  low: {
    label: "Low",
    color: "text-blue-600",
    icon: "Info",
  },
};

// export const MOCK_PATIENTS = [
//   {
//     id: 1,
//     name: "John Smith",
//     age: 45,
//     gender: "male",
//     condition: "Hypertension",
//     recentTreatments: ["Blood Pressure Medication", "Diet Consultation"],
//     insurance: "Blue Cross",
//     lastVisit: "2024-03-15",
//     status: "active",
//     upcomingAppointment: "2024-04-01",
//     priority: "medium",
//   },
//   {
//     id: 2,
//     name: "Sarah Johnson",
//     age: 32,
//     gender: "female",
//     condition: "Type 2 Diabetes",
//     recentTreatments: ["Insulin Therapy", "Nutritional Counseling"],
//     insurance: "Aetna",
//     lastVisit: "2024-03-20",
//     status: "active",
//     upcomingAppointment: "2024-04-05",
//     priority: "high",
//   },
//   {
//     id: 3,
//     name: "Michael Brown",
//     age: 58,
//     gender: "male",
//     condition: "Arthritis",
//     recentTreatments: ["Physical Therapy", "Pain Management"],
//     insurance: "Medicare",
//     lastVisit: "2024-03-10",
//     status: "inactive",
//     upcomingAppointment: null,
//     priority: "low",
//   },
//   {
//     id: 4,
//     name: "Emily Chen",
//     age: 28,
//     gender: "female",
//     condition: "Asthma",
//     recentTreatments: ["Inhaler Prescription", "Allergy Testing"],
//     insurance: "United Healthcare",
//     lastVisit: "2024-03-18",
//     status: "active",
//     upcomingAppointment: "2024-04-10",
//     priority: "medium",
//   },
//   {
//     id: 5,
//     name: "David Rodriguez",
//     age: 52,
//     gender: "male",
//     condition: "Heart Disease",
//     recentTreatments: ["Cardiac Rehabilitation", "Medication Adjustment"],
//     insurance: "Cigna",
//     lastVisit: "2024-03-05",
//     status: "pending",
//     upcomingAppointment: "2024-04-15",
//     priority: "high",
//   },
//   {
//     id: 6,
//     name: "Maria Garcia",
//     age: 19,
//     gender: "female",
//     condition: "Depression",
//     recentTreatments: ["Counseling", "Medication Management"],
//     insurance: "Medicaid",
//     lastVisit: "2024-03-22",
//     status: "active",
//     upcomingAppointment: "2024-04-08",
//     priority: "medium",
//   },
//   {
//     id: 7,
//     name: "Alex Thompson",
//     age: 41,
//     gender: "other",
//     condition: "Migraine",
//     recentTreatments: ["Pain Management", "Trigger Identification"],
//     insurance: "Kaiser",
//     lastVisit: "2024-03-12",
//     status: "inactive",
//     upcomingAppointment: null,
//     priority: "low",
//   },
//   {
//     id: 8,
//     name: "Lisa Wong",
//     age: 63,
//     gender: "female",
//     condition: "Osteoporosis",
//     recentTreatments: ["Bone Density Test", "Calcium Supplementation"],
//     insurance: "Medicare",
//     lastVisit: "2024-03-25",
//     status: "pending",
//     upcomingAppointment: "2024-04-20",
//     priority: "medium",
//   },
//   {
//     id: 9,
//     name: "James Wilson",
//     age: 16,
//     gender: "male",
//     condition: "Type 1 Diabetes",
//     recentTreatments: ["Insulin Pump Adjustment", "Dietary Planning"],
//     insurance: "Blue Shield",
//     lastVisit: "2024-03-28",
//     status: "active",
//     upcomingAppointment: "2024-04-12",
//     priority: "high",
//   },
//   {
//     id: 10,
//     name: "Sophia Patel",
//     age: 35,
//     gender: "female",
//     condition: "Anxiety",
//     recentTreatments: ["Therapy Sessions", "Stress Management"],
//     insurance: "Humana",
//     lastVisit: "2024-03-19",
//     status: "active",
//     upcomingAppointment: "2024-04-03",
//     priority: "medium",
//   },
// ];

export const INSURANCE_PROVIDERS = [
  "Blue Cross",
  "Aetna",
  "UnitedHealthcare",
  "Cigna",
  "Medicare",
  "Medicaid",
  "Kaiser Permanente",
  "Humana",
];
